### ISSUE TITLE
Makler methods

### ISSUE THREAD

**Issue by fortyoneandahalf** [fortyoneandahalf/DBISExercise3#1]
getAllMakler
addMakler
deleteMakler

**Comment by ghost** [comment]
Functions below are completed:
1. getMaklerById
2. getMaklerByLogin
3. getAllMakler
4. addMakler
5. deleteMakler

Changed hibernate.cfg.xml:
Line 19: property name="hbm2ddl.auto">update</property>

Commented out a line at Main.java:
Line 49: //service.addTestData();
